# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'M72.1.09 Gestión y análisis de datos no estructurados'
copyright = '2022, Universidad de Buenos Aires (FCE-UBA) - Profesores: Facundo Santiago, Javier Garcia Fronti'
html_title = 'M72.1.09 Gestión y análisis de datos no estructurados'
html_short_title = 'M72.1.09'
author = 'Facundo Santiago'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'myst_parser',
    'sphinx_rtd_theme',
    'sphinx.ext.todo',
    'sphinx.ext.mathjax',
    'nbsphinx',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'es'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'furo'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


myst_update_mathjax = False

# -- sphinx.ext.autosectionlabel -----------------------------------------------

# autosectionlabel_prefix_document = True
# autosectionlabel_maxdepth = 2

nbsphinx_prolog = """
.. raw:: html

  <table>
  <tr>
    <td>
    <a style="border-radius: 8px;
      box-shadow: 0 1px 2px 0 rgb(60 64 67 / 30%), 0 1px 3px 1px rgb(60 64 67 / 15%);
      font-size: 14px;
      color: #202124;
      padding: 8px 14px;
      transition: box-shadow 0.2s;
      display: flex;
      align-items: center"
        target="_blank" href="http://colab.research.google.com/github/santiagxf/{{ env.config['html_short_title'].replace('.','') }}/blob/master/docs/{{ env.doc2path(env.docname, base=None) }}">
      <img src="https://www.tensorflow.org/images/colab_logo_32px.png" style="margin-right: 8px">Abrir en Google Colab</a>
    </td>
        <td>
    <a style="border-radius: 8px;
      box-shadow: 0 1px 2px 0 rgb(60 64 67 / 30%), 0 1px 3px 1px rgb(60 64 67 / 15%);
      font-size: 14px;
      color: #202124;
      padding: 8px 14px;
      transition: box-shadow 0.2s;
      display: flex;
      align-items: center"
        href="https://raw.githubusercontent.com/santiagxf/{{ env.config['html_short_title'].replace('.','') }}/master/docs/{{ env.doc2path(env.docname, base=None) }}">
      <img src="https://www.tensorflow.org/images/download_logo_32px.png" style="margin-right: 8px">Descargar notebook</a>
    </td>
  </tr>
  </table>
"""